
import React, { useRef, useState } from 'react';
import type { EnhancedTitanSchema } from '../types';
import { trackEvent } from '../services/analyticsService';
import { KeyMetrics } from './KeyMetrics';
import { RiskAssessment } from './RiskAssessment';
import { Insights } from './Insights';
import { Recommendation } from './Recommendation';
import { SummaryHeader } from './SummaryHeader';
import { LightbulbIcon, UserIcon, ChartBarIcon, ShareIcon } from './icons/Icons';

interface SummaryCardProps {
  data: EnhancedTitanSchema;
  isSelected: boolean;
  onToggleSelection: (id: string) => void;
  onExportPDF: (element: HTMLDivElement | null, data: EnhancedTitanSchema) => void;
  isExporting: boolean;
}

type Perspective = 'analyst' | 'simple' | 'human';

const Disclaimer: React.FC = () => (
    <div className="mb-4 px-4 py-3 bg-warning-amber/10 border border-warning-amber/30 rounded-lg">
      <p className="text-xs text-gray-400 flex items-start gap-2">
        <span className="text-warning-amber text-sm mt-0.5">⚠️</span>
        <span>
          <strong className="text-warning-amber">Educational Analysis:</strong> This summary is generated by AI using publicly available information. 
          For investment decisions, always verify with official sources at{' '}
          <a href="https://www.sec.gov" target="_blank" rel="noopener noreferrer" className="underline hover:text-warning-amber transition-colors">
            sec.gov
          </a>. Not financial advice.
        </span>
      </p>
    </div>
);

const PerspectiveTabs: React.FC<{ active: Perspective, setActive: (p: Perspective) => void }> = ({ active, setActive }) => {
    const tabs: { id: Perspective, label: string, icon: React.ReactNode }[] = [
        { id: 'simple', label: 'Simple', icon: <LightbulbIcon className="w-5 h-5" /> },
        { id: 'human', label: 'Human', icon: <UserIcon className="w-5 h-5" /> },
        { id: 'analyst', label: 'Analyst', icon: <ChartBarIcon className="w-5 h-5" /> },
    ];

    const getTabClass = (tabId: Perspective) => {
        return active === tabId
            ? 'bg-accent-cyan text-base-graphite'
            : 'bg-gray-800/60 text-gray-400 hover:bg-gray-700/80';
    };

    return (
        <div className="mb-6 flex items-center justify-center p-1 bg-base-graphite rounded-lg border border-gray-800/70">
            {tabs.map(tab => (
                 <button
                    key={tab.id}
                    onClick={() => setActive(tab.id)}
                    className={`flex-1 flex items-center justify-center gap-2 px-4 py-2 text-sm font-semibold rounded-md transition-all ${getTabClass(tab.id)}`}
                 >
                    {tab.icon}
                    <span>{tab.label}</span>
                </button>
            ))}
        </div>
    );
};

export const SummaryCard: React.FC<SummaryCardProps> = ({ data, isSelected, onToggleSelection, onExportPDF, isExporting }) => {
    const [activePerspective, setActivePerspective] = useState<Perspective>('simple');
    const [isLinkCopied, setIsLinkCopied] = useState(false);
    const pdfRef = useRef<HTMLDivElement>(null);

    const perspectiveData = data.perspectives[activePerspective];

    const handleSetPerspective = (p: Perspective) => {
        setActivePerspective(p);
        trackEvent('change_perspective', { perspective: p, ticker: data.meta.ticker });
    }

    const handleShare = async () => {
        try {
            const jsonString = JSON.stringify(data);
            const encodedData = encodeURIComponent(btoa(jsonString));
            const url = `${window.location.origin}${window.location.pathname}?summary=${encodedData}`;

            const shareMethod = navigator.share ? 'native' : 'clipboard';
            trackEvent('share_summary', { ticker: data.meta.ticker, method: shareMethod });

            if (navigator.share) {
                await navigator.share({
                    title: `Financial Summary for ${data.meta.ticker}`,
                    text: `Check out this AI-generated financial summary for ${data.meta.company_name}.`,
                    url: url,
                });
            } else {
                await navigator.clipboard.writeText(url);
                setIsLinkCopied(true);
                setTimeout(() => setIsLinkCopied(false), 2000);
            }
        } catch (error) {
            console.error('Failed to share:', error);
            trackEvent('share_summary_error', { ticker: data.meta.ticker });
            alert('Failed to share summary.');
        }
    };

    return (
        <div className={`transition-all duration-300 ${isSelected ? 'ring-2 ring-highlight-gold rounded-lg' : ''}`}>
            <div ref={pdfRef} className="dashboard-background p-1 rounded-lg">
                <div className="p-4 md:p-6 bg-base-graphite rounded-lg">
                    <Disclaimer />
                    <SummaryHeader meta={data.meta} summary={data.perspectives.analyst.summary} />
                    
                    <div className="mt-6">
                        <PerspectiveTabs active={activePerspective} setActive={handleSetPerspective} />
                    </div>

                    <div className="mt-6 space-y-6">
                        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                            <div className="lg:col-span-2 space-y-6">
                                <KeyMetrics metrics={perspectiveData.key_metrics} currency={data.meta.currency} />
                                <Insights insights={perspectiveData.insights} />
                            </div>
                            <div className="lg:col-span-1">
                                <RiskAssessment assessment={perspectiveData.risk_assessment} />
                            </div>
                        </div>
                        <Recommendation recommendation={perspectiveData.recommendation} />
                    </div>
                </div>
            </div>

            <div className="mt-4 flex items-center justify-between">
                <label className="flex items-center space-x-2 cursor-pointer">
                    <input
                        type="checkbox"
                        checked={isSelected}
                        onChange={() => onToggleSelection(data.id)}
                        className="form-checkbox h-5 w-5 rounded bg-gray-800 border-gray-600 text-highlight-gold focus:ring-highlight-gold"
                    />
                    <span className="text-gray-400">Select for Comparison</span>
                </label>
                 <div className="flex items-center space-x-2">
                    <button
                        onClick={handleShare}
                        className="px-4 py-2 text-sm font-semibold text-highlight-gold bg-highlight-gold/10 border border-highlight-gold/50 rounded-md hover:bg-highlight-gold/20 transition-colors flex items-center gap-2"
                    >
                        <ShareIcon className="w-4 h-4" />
                        {isLinkCopied ? 'Link Copied!' : 'Share'}
                    </button>
                    <button
                        onClick={() => onExportPDF(pdfRef.current, data)}
                        disabled={isExporting}
                        className="px-4 py-2 text-sm font-semibold text-accent-cyan bg-accent-cyan/10 border border-accent-cyan/50 rounded-md hover:bg-accent-cyan/20 transition-colors disabled:opacity-50 disabled:cursor-wait"
                    >
                        {isExporting ? 'Exporting...' : 'Export as PDF'}
                    </button>
                </div>
            </div>
        </div>
    );
};